[package]
name = "kasino"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = []
std = ["alloc"]
alloc = []
instrumented = []
atomic-fallback = ["portable-atomic/fallback"]

[dependencies]
crossbeam-utils = { workspace = true }
portable-atomic = { version = "1.13.1", default-features = false, features = ["require-cas"] }
rand = { version = "0.10.2", default-features = false }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
spin = { version = "0.12.0", features = ["lock_api", "rwlock"] }
crossbeam-queue = "0.3.12"

[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = ["checkpoint"] }

[target.'cfg(shuttle)'.dependencies]
shuttle = "0.9"

[lints]
workspace = true

[[bench]]
name = "main_benchmarks"
harness = false
